data:
  source:
    - https://seelabutk-data.s3.amazonaws.com/turbine_VMIN_EPS1.7_minPts40_X1589_Y698_Z1799_Full.raw


#docker:
#  port: 6688
#  replicas: 1


#aws:
#  bucket: {{YOUR-S3-BUCKET-NAME}}
#  # https: true
#  region: us-east-2
#  managers:
#    'm5.8xlarge': 1


tapestry:
  directory:
    - {{/ABSOLUTE/PATH/TO/THIS/DIRECTORY}}/tapestry
