data:
  source:
    - {/ABSOLUTE/PATH/TO/DIRECTORY/WITH/DATASET}


#docker:
#  port: 6688
#  replicas: 1


#aws:
#  bucket: {{YOUR-S3-BUCKET-NAME}}
#  region: us-east-2
#  managers:
#    'm5.8xlarge': 1


tapestry:
  directory:
    - {/ABSOLUTE/PATH/TO/THIS/DIRECTORY}/tapestry
