data:
  source:
    - data/turbine.raw


#docker:
#  port: 6688
#  replicas: 1


#aws:
#  bucket: {{YOUR-S3-BUCKET-NAME}}
#  region: us-east-2
#  managers:
#    'm5.8xlarge': 1


tapestry:
  directory:
    - {{PATH/TO/THIS/DIRECTORY}}/tapestry
